### ISSUE TITLE
Something wrong with the poly mulitiplication

### ISSUE THREAD

**Issue by Lucas-Wye** [acmert/bfv-python#3]
As I used your code, I find that there are two method to do multiplication in the file `poly.py`.
But the results are different.
Here is the example code:
```
# method 1
c_poly = a_poly.toNTT() * b_poly.toNTT()
c_ref = c_poly.toPOL().F

# method 2
c_poly = a_poly * b_poly
c_ref = c_poly.F
```
The results `c_ref` are different. 
I want to ask if there is anything wrong with the code?
Thank you.

**Comment by acmert** [comment]
If both `a_poly` and `b_poly` are in POLY domain, then `def __mul__(self, b)` performs the first method. It first transforms `a_poly` and `b_poly` into the NTT domain, performs coefficient-wise multiplication and transforms the resulting `c_poly` into POLY domain.

If both `a_poly` and `b_poly` are already in NTT domain, then `def __mul__(self, b)` just performs coefficient-wise multiplication operation and generates a result in NTT domain.

Thus, two methods are expected to generate different results.

**Comment by Lucas-Wye** [comment]
Thank you!
